export namespace Configuracion {
  export const mensajeCambioClave = "se ha modificado tu contraseña en el sistema "
  export const mensajeRecuperarClave = "su nueva contraseña solicitada es: "
  export const asuntoUsuarioCreado = "Registro en la plataforma"
  export const mensajeUsuarioCreado = "se ha registrado tu correo electrónico en la plataforma, su correo servira como usuario y su contraseña es: "
  export const hashNotificacion = "dXUyW6uvq6"
  export const urlCorreo = "http://localhost:5000/correo"
  export const urlSms = "http://localhost:5000/enviar-texto"
  export const asuntoCambioClave = "Cambio de contraseña"
  export const saludo = "Hola"
  export const destinoArg = "destino"
  export const asuntoArg = "asunto"
  export const mensajeArg = "mensaje"
  export const hashArg = "hash"
}
